/* Automatic generated by './build/bin/build-entry.js' */

import Button from '../src/components/button/index.js'
import Navbar from '../src/components/navbar/index.js'
const plugins = [
  Button,
  Navbar
]
const install = function(Vue, opts = {}) {
  /* istanbul ignore if */
  if (install.installed) return

  plugins.map(plugin => {
    Vue.use(plugin)
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '1.0.0',
  install,
  Button,
  Navbar
}
